import type { Metadata } from "next";
import "./globals.css";
import ReduxProviderComponent from "@/redux/redux-provider-component";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "FitLand",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <ReduxProviderComponent>{children}</ReduxProviderComponent>
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
