import type { Metadata } from "next";
import "./globals.css";
import ReduxProviderComponent from "@/redux/redux-provider-component";

export const metadata: Metadata = {
  title: "FitLand",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProviderComponent>{children}</ReduxProviderComponent>
      </body>
    </html>
  );
}
