import { Province, City } from "./mock-data.types";

export const provinces: Province[] = [
  { id: 1, name: "تهران" },
  { id: 2, name: "اصفهان" },
  { id: 3, name: "فارس" },
  { id: 4, name: "خراسان رضوی" },
  { id: 5, name: "خوزستان" },
  { id: 6, name: "آذربایجان شرقی" },
  { id: 7, name: "مازندران" },
  { id: 8, name: "کرمان" },
  { id: 9, name: "آذربایجان غربی" },
  { id: 10, name: "گیلان" },
  { id: 11, name: "هرمزگان" },
  { id: 12, name: "سیستان و بلوچستان" },
  { id: 13, name: "کرمانشاه" },
  { id: 14, name: "مرکزی" },
  { id: 15, name: "لرستان" },
  { id: 16, name: "همدان" },
  { id: 17, name: "گلستان" },
  { id: 18, name: "قزوین" },
  { id: 19, name: "اردبیل" },
  { id: 20, name: "یزد" },
  { id: 21, name: "قم" },
  { id: 22, name: "زنجان" },
  { id: 23, name: "سمنان" },
  { id: 24, name: "کهگیلویه و بویراحمد" },
  { id: 25, name: "بوشهر" },
  { id: 26, name: "چهارمحال و بختیاری" },
  { id: 27, name: "ایلام" },
  { id: 28, name: "خراسان شمالی" },
  { id: 29, name: "خراسان جنوبی" },
  { id: 30, name: "البرز" },
];

export const cities: City[] = [
  { id: 1, name: "تهران", provinceId: 1 },
  { id: 2, name: "شهریار", provinceId: 1 },
  { id: 3, name: "ری", provinceId: 1 },
  { id: 4, name: "ورامین", provinceId: 1 },
  { id: 5, name: "دماوند", provinceId: 1 },
  { id: 6, name: "پاکدشت", provinceId: 1 },
  { id: 7, name: "اسلامشهر", provinceId: 1 },
  { id: 8, name: "رباط کریم", provinceId: 1 },
  { id: 9, name: "شمیرانات", provinceId: 1 },
  { id: 10, name: "فیروزکوه", provinceId: 1 },
  { id: 11, name: "اصفهان", provinceId: 2 },
  { id: 12, name: "کاشان", provinceId: 2 },
  { id: 13, name: "نجف آباد", provinceId: 2 },
  { id: 14, name: "خمینی شهر", provinceId: 2 },
  { id: 15, name: "شاهین شهر", provinceId: 2 },
  { id: 16, name: "نطنز", provinceId: 2 },
  { id: 17, name: "فلاورجان", provinceId: 2 },
  { id: 18, name: "گلپایگان", provinceId: 2 },
  { id: 19, name: "نایین", provinceId: 2 },
  { id: 20, name: "آران و بیدگل", provinceId: 2 },
  { id: 21, name: "شیراز", provinceId: 3 },
  { id: 22, name: "مرودشت", provinceId: 3 },
  { id: 23, name: "کازرون", provinceId: 3 },
  { id: 24, name: "جهرم", provinceId: 3 },
  { id: 25, name: "لار", provinceId: 3 },
  { id: 26, name: "فسا", provinceId: 3 },
  { id: 27, name: "داراب", provinceId: 3 },
  { id: 28, name: "آباده", provinceId: 3 },
  { id: 29, name: "سپیدان", provinceId: 3 },
  { id: 30, name: "فیروزآباد", provinceId: 3 },
  { id: 31, name: "مشهد", provinceId: 4 },
  { id: 32, name: "نیشابور", provinceId: 4 },
  { id: 33, name: "سبزوار", provinceId: 4 },
  { id: 34, name: "تربت حیدریه", provinceId: 4 },
  { id: 35, name: "قوچان", provinceId: 4 },
  { id: 36, name: "گناباد", provinceId: 4 },
  { id: 37, name: "کاشمر", provinceId: 4 },
  { id: 38, name: "تربت جام", provinceId: 4 },
  { id: 39, name: "چناران", provinceId: 4 },
  { id: 40, name: "فریمان", provinceId: 4 },
  { id: 41, name: "اهواز", provinceId: 5 },
  { id: 42, name: "دزفول", provinceId: 5 },
  { id: 43, name: "آبادان", provinceId: 5 },
  { id: 44, name: "خرمشهر", provinceId: 5 },
  { id: 45, name: "اندیمشک", provinceId: 5 },
  { id: 46, name: "بهبهان", provinceId: 5 },
  { id: 47, name: "ماهشهر", provinceId: 5 },
  { id: 48, name: "شوشتر", provinceId: 5 },
  { id: 49, name: "ایذه", provinceId: 5 },
  { id: 50, name: "رامهرمز", provinceId: 5 },
  { id: 51, name: "تبریز", provinceId: 6 },
  { id: 52, name: "مراغه", provinceId: 6 },
  { id: 53, name: "مرند", provinceId: 6 },
  { id: 54, name: "میانه", provinceId: 6 },
  { id: 55, name: "شبستر", provinceId: 6 },
  { id: 56, name: "بناب", provinceId: 6 },
  { id: 57, name: "سراب", provinceId: 6 },
  { id: 58, name: "هشترود", provinceId: 6 },
  { id: 59, name: "اهر", provinceId: 6 },
  { id: 60, name: "ملکان", provinceId: 6 },
  { id: 61, name: "ساری", provinceId: 7 },
  { id: 62, name: "آمل", provinceId: 7 },
  { id: 63, name: "بابل", provinceId: 7 },
  { id: 64, name: "قائم شهر", provinceId: 7 },
  { id: 65, name: "بهشهر", provinceId: 7 },
  { id: 66, name: "تنکابن", provinceId: 7 },
  { id: 67, name: "چالوس", provinceId: 7 },
  { id: 68, name: "نوشهر", provinceId: 7 },
  { id: 69, name: "نور", provinceId: 7 },
  { id: 70, name: "رامسر", provinceId: 7 },
  { id: 71, name: "کرمان", provinceId: 8 },
  { id: 72, name: "رفسنجان", provinceId: 8 },
  { id: 73, name: "سیرجان", provinceId: 8 },
  { id: 74, name: "جیرفت", provinceId: 8 },
  { id: 75, name: "بم", provinceId: 8 },
  { id: 76, name: "زرند", provinceId: 8 },
  { id: 77, name: "شهربابک", provinceId: 8 },
  { id: 78, name: "کهنوج", provinceId: 8 },
  { id: 79, name: "بافت", provinceId: 8 },
  { id: 80, name: "راور", provinceId: 8 },
  { id: 81, name: "ارومیه", provinceId: 9 },
  { id: 82, name: "خوی", provinceId: 9 },
  { id: 83, name: "مهاباد", provinceId: 9 },
  { id: 84, name: "بوکان", provinceId: 9 },
  { id: 85, name: "میاندوآب", provinceId: 9 },
  { id: 86, name: "سلماس", provinceId: 9 },
  { id: 87, name: "نقده", provinceId: 9 },
  { id: 88, name: "پیرانشهر", provinceId: 9 },
  { id: 89, name: "سردشت", provinceId: 9 },
  { id: 90, name: "تکاب", provinceId: 9 },
  { id: 91, name: "رشت", provinceId: 10 },
  { id: 92, name: "بندر انزلی", provinceId: 10 },
  { id: 93, name: "لاهیجان", provinceId: 10 },
  { id: 94, name: "لنگرود", provinceId: 10 },
  { id: 95, name: "رودسر", provinceId: 10 },
  { id: 96, name: "تالش", provinceId: 10 },
  { id: 97, name: "آستارا", provinceId: 10 },
  { id: 98, name: "صومعه سرا", provinceId: 10 },
  { id: 99, name: "فومن", provinceId: 10 },
  { id: 100, name: "ماسال", provinceId: 10 },
  { id: 101, name: "بندرعباس", provinceId: 11 },
  { id: 102, name: "میناب", provinceId: 11 },
  { id: 103, name: "بندر لنگه", provinceId: 11 },
  { id: 104, name: "قشم", provinceId: 11 },
  { id: 105, name: "جاسک", provinceId: 11 },
  { id: 106, name: "کیش", provinceId: 11 },
  { id: 107, name: "حاجی آباد", provinceId: 11 },
  { id: 108, name: "رودان", provinceId: 11 },
  { id: 109, name: "بستک", provinceId: 11 },
  { id: 110, name: "ابوموسی", provinceId: 11 },
  { id: 111, name: "زاهدان", provinceId: 12 },
  { id: 112, name: "زابل", provinceId: 12 },
  { id: 113, name: "چابهار", provinceId: 12 },
  { id: 114, name: "ایرانشهر", provinceId: 12 },
  { id: 115, name: "خاش", provinceId: 12 },
  { id: 116, name: "سراوان", provinceId: 12 },
  { id: 117, name: "نیکشهر", provinceId: 12 },
  { id: 118, name: "کنارک", provinceId: 12 },
  { id: 119, name: "سرباز", provinceId: 12 },
  { id: 120, name: "میرجاوه", provinceId: 12 },
  { id: 121, name: "کرمانشاه", provinceId: 13 },
  { id: 122, name: "اسلام آباد غرب", provinceId: 13 },
  { id: 123, name: "پاوه", provinceId: 13 },
  { id: 124, name: "سنقر", provinceId: 13 },
  { id: 125, name: "هرسین", provinceId: 13 },
  { id: 126, name: "کنگاور", provinceId: 13 },
  { id: 127, name: "صحنه", provinceId: 13 },
  { id: 128, name: "جوانرود", provinceId: 13 },
  { id: 129, name: "قصر شیرین", provinceId: 13 },
  { id: 130, name: "گیلان غرب", provinceId: 13 },
  { id: 131, name: "اراک", provinceId: 14 },
  { id: 132, name: "ساوه", provinceId: 14 },
  { id: 133, name: "خمین", provinceId: 14 },
  { id: 134, name: "محلات", provinceId: 14 },
  { id: 135, name: "دلیجان", provinceId: 14 },
  { id: 136, name: "تفرش", provinceId: 14 },
  { id: 137, name: "شازند", provinceId: 14 },
  { id: 138, name: "آشتیان", provinceId: 14 },
  { id: 139, name: "زرندیه", provinceId: 14 },
  { id: 140, name: "کمیجان", provinceId: 14 },
  { id: 141, name: "خرم آباد", provinceId: 15 },
  { id: 142, name: "بروجرد", provinceId: 15 },
  { id: 143, name: "دورود", provinceId: 15 },
  { id: 144, name: "الیگودرز", provinceId: 15 },
  { id: 145, name: "ازنا", provinceId: 15 },
  { id: 146, name: "نورآباد", provinceId: 15 },
  { id: 147, name: "کوهدشت", provinceId: 15 },
  { id: 148, name: "الشتر", provinceId: 15 },
  { id: 149, name: "پلدختر", provinceId: 15 },
  { id: 150, name: "دلفان", provinceId: 15 },
  { id: 151, name: "همدان", provinceId: 16 },
  { id: 152, name: "ملایر", provinceId: 16 },
  { id: 153, name: "نهاوند", provinceId: 16 },
  { id: 154, name: "تویسرکان", provinceId: 16 },
  { id: 155, name: "کبودرآهنگ", provinceId: 16 },
  { id: 156, name: "اسدآباد", provinceId: 16 },
  { id: 157, name: "رزن", provinceId: 16 },
  { id: 158, name: "بهار", provinceId: 16 },
  { id: 159, name: "فامنین", provinceId: 16 },
  { id: 160, name: "درگزین", provinceId: 16 },
  { id: 161, name: "گرگان", provinceId: 17 },
  { id: 162, name: "گنبد کاووس", provinceId: 17 },
  { id: 163, name: "علی آباد", provinceId: 17 },
  { id: 164, name: "آق قلا", provinceId: 17 },
  { id: 165, name: "مینودشت", provinceId: 17 },
  { id: 166, name: "کردکوی", provinceId: 17 },
  { id: 167, name: "بندر گز", provinceId: 17 },
  { id: 168, name: "آزادشهر", provinceId: 17 },
  { id: 169, name: "کلاله", provinceId: 17 },
  { id: 170, name: "رامیان", provinceId: 17 },
  { id: 171, name: "قزوین", provinceId: 18 },
  { id: 172, name: "تاکستان", provinceId: 18 },
  { id: 173, name: "آبیک", provinceId: 18 },
  { id: 174, name: "بوئین زهرا", provinceId: 18 },
  { id: 175, name: "البرز", provinceId: 18 },
  { id: 176, name: "آوج", provinceId: 18 },
  { id: 177, name: "اردبیل", provinceId: 19 },
  { id: 178, name: "پارس آباد", provinceId: 19 },
  { id: 179, name: "خلخال", provinceId: 19 },
  { id: 180, name: "مشگین شهر", provinceId: 19 },
  { id: 181, name: "گرمی", provinceId: 19 },
  { id: 182, name: "نمین", provinceId: 19 },
  { id: 183, name: "نیر", provinceId: 19 },
  { id: 184, name: "سرعین", provinceId: 19 },
  { id: 185, name: "کوثر", provinceId: 19 },
  { id: 186, name: "بیله سوار", provinceId: 19 },
  { id: 187, name: "یزد", provinceId: 20 },
  { id: 188, name: "میبد", provinceId: 20 },
  { id: 189, name: "اردکان", provinceId: 20 },
  { id: 190, name: "مهریز", provinceId: 20 },
  { id: 191, name: "تفت", provinceId: 20 },
  { id: 192, name: "ابرکوه", provinceId: 20 },
  { id: 193, name: "بافق", provinceId: 20 },
  { id: 194, name: "هرات", provinceId: 20 },
  { id: 195, name: "خاتم", provinceId: 20 },
  { id: 196, name: "طبس", provinceId: 20 },
  { id: 197, name: "قم", provinceId: 21 },
  { id: 198, name: "زنجان", provinceId: 22 },
  { id: 199, name: "ابهر", provinceId: 22 },
  { id: 200, name: "خدابنده", provinceId: 22 },
  { id: 201, name: "خرمدره", provinceId: 22 },
  { id: 202, name: "طارم", provinceId: 22 },
  { id: 203, name: "ماهنشان", provinceId: 22 },
  { id: 204, name: "قیدار", provinceId: 22 },
  { id: 205, name: "ایجرود", provinceId: 22 },
  { id: 206, name: "سمنان", provinceId: 23 },
  { id: 207, name: "شاهرود", provinceId: 23 },
  { id: 208, name: "دامغان", provinceId: 23 },
  { id: 209, name: "گرمسار", provinceId: 23 },
  { id: 210, name: "مهدی شهر", provinceId: 23 },
  { id: 211, name: "سرخه", provinceId: 23 },
  { id: 212, name: "میامی", provinceId: 23 },
  { id: 213, name: "آرادان", provinceId: 23 },
  { id: 214, name: "یاسوج", provinceId: 24 },
  { id: 215, name: "دهدشت", provinceId: 24 },
  { id: 216, name: "دوگنبدان", provinceId: 24 },
  { id: 217, name: "سی سخت", provinceId: 24 },
  { id: 218, name: "دنا", provinceId: 24 },
  { id: 219, name: "لنده", provinceId: 24 },
  { id: 220, name: "بویراحمد", provinceId: 24 },
  { id: 221, name: "بوشهر", provinceId: 25 },
  { id: 222, name: "برازجان", provinceId: 25 },
  { id: 223, name: "کنگان", provinceId: 25 },
  { id: 224, name: "گناوه", provinceId: 25 },
  { id: 225, name: "دیر", provinceId: 25 },
  { id: 226, name: "دیلم", provinceId: 25 },
  { id: 227, name: "عسلویه", provinceId: 25 },
  { id: 228, name: "جم", provinceId: 25 },
  { id: 229, name: "دشتستان", provinceId: 25 },
  { id: 230, name: "شهرکرد", provinceId: 26 },
  { id: 231, name: "بروجن", provinceId: 26 },
  { id: 232, name: "فارسان", provinceId: 26 },
  { id: 233, name: "لردگان", provinceId: 26 },
  { id: 234, name: "اردل", provinceId: 26 },
  { id: 235, name: "کوهرنگ", provinceId: 26 },
  { id: 236, name: "کیار", provinceId: 26 },
  { id: 237, name: "ایلام", provinceId: 27 },
  { id: 238, name: "دهلران", provinceId: 27 },
  { id: 239, name: "آبدانان", provinceId: 27 },
  { id: 240, name: "ایوان", provinceId: 27 },
  { id: 241, name: "مهران", provinceId: 27 },
  { id: 242, name: "دره شهر", provinceId: 27 },
  { id: 243, name: "شیروان و چرداول", provinceId: 27 },
  { id: 244, name: "ملکشاهی", provinceId: 27 },
  { id: 245, name: "بجنورد", provinceId: 28 },
  { id: 246, name: "شیروان", provinceId: 28 },
  { id: 247, name: "اسفراین", provinceId: 28 },
  { id: 248, name: "جاجرم", provinceId: 28 },
  { id: 249, name: "فاروج", provinceId: 28 },
  { id: 250, name: "گرمه", provinceId: 28 },
  { id: 251, name: "راز و جرگلان", provinceId: 28 },
  { id: 252, name: "مانه و سملقان", provinceId: 28 },
  { id: 253, name: "بیرجند", provinceId: 29 },
  { id: 254, name: "قائنات", provinceId: 29 },
  { id: 255, name: "فردوس", provinceId: 29 },
  { id: 256, name: "طبس", provinceId: 29 },
  { id: 257, name: "نهبندان", provinceId: 29 },
  { id: 258, name: "سرایان", provinceId: 29 },
  { id: 259, name: "سربیشه", provinceId: 29 },
  { id: 260, name: "درمیان", provinceId: 29 },
  { id: 261, name: "کرج", provinceId: 30 },
  { id: 262, name: "نظرآباد", provinceId: 30 },
  { id: 263, name: "ساوجبلاغ", provinceId: 30 },
  { id: 264, name: "طالقان", provinceId: 30 },
  { id: 265, name: "اشتهارد", provinceId: 30 },
  { id: 266, name: "فردیس", provinceId: 30 },
  { id: 267, name: "هشتگرد", provinceId: 30 },
  { id: 268, name: "محمدشهر", provinceId: 30 },
];
