const cardData = [
    {
        imageSrc: "/image/borwn-showse.png",
        title: "Brown Shoes",
        minSize: "lg",
        maxSize: "xl",
        price: "99.99",
        discountedPrice: "79.99",
        numberActiveStars: "5",
        classNameColorProducts: ["bg-zinc-500", "bg-zinc-100", "bg-zinc-500"],
    },
    {
        imageSrc: "/image/borwn-showse.png",
        title: "Brown Shoes",
        minSize: "lg",
        maxSize: "xl",
        price: "99.99",
        discountedPrice: "79.99",
        numberActiveStars: "3",
        classNameColorProducts: ["bg-zinc-500", "bg-zinc-100", "bg-zinc-500"],
    },
    {
        imageSrc: "/image/borwn-showse.png",
        title: "Brown Shoes",
        minSize: "lg",
        maxSize: "xl",
        price: "99.99",
        discountedPrice: "79.99",
        numberActiveStars: "4",
        classNameColorProducts: ["bg-zinc-500", "bg-zinc-100", "bg-zinc-500"],
    },
    {
        imageSrc: "/image/borwn-showse.png",
        title: "Brown Shoes",
        minSize: "lg",
        maxSize: "xl",
        price: "99.99",
        discountedPrice: "79.99",
        numberActiveStars: "1",
        classNameColorProducts: ["bg-zinc-500", "bg-zinc-100", "bg-zinc-500"],
    },
]?.map((items, index) => ({ ...items, id: String(index + 1) }));
export default cardData;